# Generated by Django 3.2.16 on 2022-12-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
